// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_flow/test/features/kanban/data/repositories/kanban_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kanban_flow/features/kanban/data/datasources/kanban_local_datasource.dart'
    as _i2;
import 'package:kanban_flow/features/kanban/data/models/board_model.dart'
    as _i4;
import 'package:kanban_flow/features/kanban/data/models/column_model.dart'
    as _i5;
import 'package:kanban_flow/features/kanban/data/models/task_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [KanbanLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanbanLocalDataSource extends _i1.Mock
    implements _i2.KanbanLocalDataSource {
  MockKanbanLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BoardModel>> getBoards() =>
      (super.noSuchMethod(
            Invocation.method(#getBoards, []),
            returnValue: _i3.Future<List<_i4.BoardModel>>.value(
              <_i4.BoardModel>[],
            ),
          )
          as _i3.Future<List<_i4.BoardModel>>);

  @override
  _i3.Future<void> createBoard(_i4.BoardModel? board) =>
      (super.noSuchMethod(
            Invocation.method(#createBoard, [board]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBoard(String? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBoard, [boardId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ColumnModel>> getColumns(String? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#getColumns, [boardId]),
            returnValue: _i3.Future<List<_i5.ColumnModel>>.value(
              <_i5.ColumnModel>[],
            ),
          )
          as _i3.Future<List<_i5.ColumnModel>>);

  @override
  _i3.Future<void> createColumn(_i5.ColumnModel? column) =>
      (super.noSuchMethod(
            Invocation.method(#createColumn, [column]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteColumn(String? columnId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteColumn, [columnId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.TaskModel>> getTasks(String? columnId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [columnId]),
            returnValue: _i3.Future<List<_i6.TaskModel>>.value(
              <_i6.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i6.TaskModel>>);

  @override
  _i3.Future<void> createTask(_i6.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTask(_i6.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.TaskModel>> searchTasks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [query]),
            returnValue: _i3.Future<List<_i6.TaskModel>>.value(
              <_i6.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i6.TaskModel>>);
}
